---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by larryhou.
--- DateTime: 2019/12/19 11:01 AM
---


do
    x = 12345678
    print(x, _ENV.x, _G.x, _ENV)
end


do
    env = {__index = _G}
    setmetatable(env, env)
    _ENV = env
    print(x)
end

y = 100

do
    print(_ENV)
end 

print(_G.y, _ENV.y, _ENV)